### ISSUE TITLE
Documentation not up-to-date

### ISSUE THREAD

**Issue by Saran-nns** [bioAI-Oslo/Spikeometric#15]
Hi Team,

Test run for an example in the documentation breaks. 

Please check the error at https://colab.research.google.com/drive/1l8Y3So5uBXl4kA_6jvpkvyZOILVjdrHK#scrollTo=Ya0jZquvtSXZ&line=6&uniqifier=1

Also, for reference, it would be useful to mention the imports at each code blocks

thanks,
saran

https://github.com/openjournals/joss-reviews/issues/5451#issuecomment-1682651871

**Comment by JakobSonstebo** [comment]
Hi!

Thank you, you're right this was not updated last time a change was made to the parameter names. I've corrected interval to period and duration to stop in the introduction document now. Please let me know if you find any other inconsistencies between the documentation and the source, so I can correct them as quickly as possible.

Jakob
