### ISSUE TITLE
SA models return 100 extra timesteps

### ISSUE THREAD

**Issue by lepmik** [bioAI-Oslo/Spikeometric#24]
https://github.com/bioAI-Oslo/Spikeometric/blob/c6b4961d69bdc671c4f17e82b8e689424f23d353/spikeometric/models/sa_model.py#L71

Should this be `x[:,T:]`?

**Comment by JakobSonstebo** [comment]
Yes, thank you! I have updated the equilibration function for the SA models and the forward function so that it doesn't return the equilibration time steps.
